INSERT INTO estudiantes (nombre_estudiante, pregrado, semestre, curso_inscrito)
VALUES
('Juan Pérez', 'Ingeniería de Sistemas', 3, 'Desarrollo de videojuegos'),
('María Gómez', 'Comunicación Social', 5, 'Montaje audiovisual'),
('Carlos Rodríguez', 'Administración de Empresas', 7, 'Gestión de marcas'),
('Laura Fernández', 'Psicología', 4, 'Sostenibilidad y economía circular'),
('Andrés Morales', 'Ingeniería Civil', 6, 'Diseño en estructuras de acero'),
('Paula Restrepo', 'Derecho', 2, 'Blockchain y Web 3.0'),
('Felipe Torres', 'Mercadeo', 8, 'Marketing digital y comercio electrónico'),
('Sofía Ramírez', 'Diseño Gráfico', 5, 'Diseño gráfico para redes sociales'),
('Camilo Arias', 'Ingeniería Industrial', 9, 'Gestión logística en cadena de suministro'),
('Valentina López', 'Ingeniería de Sistemas', 1, 'Inteligencia artificial para mercadeo'),
('Daniel Mejía', 'Comunicación Social', 6, 'Animación digital'),
('Isabella Quintero', 'Administración de Empresas', 4, 'Transformación digital en empresas'),
('Santiago Castaño', 'Psicología', 3, 'Gestión del talento humano e innovación organizacional'),
('Sara Ríos', 'Derecho', 7, 'Big Data y analítica de negocios'),
('Tomás Villa', 'Ingeniería Civil', 10, 'Gestión de proyectos de construcción sostenible'),
('Mariana Herrera', 'Mercadeo', 2, 'Producción audiovisual para el metaverso'),
('Esteban Salazar', 'Diseño Gráfico', 5, 'Fotografía comercial'),
('Antonella Vélez', 'Ingeniería Industrial', 8, 'Economía circular y sostenibilidad'),
('Nicolás Pineda', 'Ingeniería de Sistemas', 6, 'Blockchain y Web 3.0'),
('Luciana Guerra', 'Comunicación Social', 9, 'Sonido y producción musical'),
('Julián Zapata', 'Administración de Empresas', 1, 'Gestión de marcas'),
('Manuela Arias', 'Psicología', 5, 'Diseño agroecológico regenerativo'),
('David Ortiz', 'Derecho', 4, 'Inteligencia artificial para mercadeo'),
('Gabriela Molina', 'Mercadeo', 3, 'Marketing digital y comercio electrónico'),
('Samuel Rojas', 'Diseño Gráfico', 7, 'Animación digital'),
('Martina García', 'Ingeniería Industrial', 6, 'Transformación digital en empresas'),
('Emiliano Ángel', 'Ingeniería de Sistemas', 8, 'Desarrollo de videojuegos'),
('Valeria Zapata', 'Comunicación Social', 4, 'Fotografía comercial'),
('Juan David Suárez', 'Administración de Empresas', 2, 'Gestión logística en cadena de suministro'),
('María Paula Cano', 'Psicología', 6, 'Gestión del talento humano e innovación organizacional'),
('Sebastián López', 'Derecho', 9, 'Blockchain y Web 3.0'),
('Ana Sofía Rivera', 'Mercadeo', 1, 'Producción audiovisual para el metaverso'),
('Mateo Sánchez', 'Diseño Gráfico', 3, 'Diseño gráfico para redes sociales'),
('Juliana Orozco', 'Ingeniería Industrial', 7, 'Big Data y analítica de negocios'),
('Tomás Herrera', 'Ingeniería de Sistemas', 5, 'Inteligencia artificial para mercadeo'),
('María José Londoño', 'Comunicación Social', 8, 'Sonido y producción musical'),
('David Cárdenas', 'Administración de Empresas', 6, 'Economía circular y sostenibilidad'),
('Salomé Gómez', 'Psicología', 2, 'Diseño agroecológico regenerativo'),
('Juan Sebastián Ríos', 'Derecho', 4, 'Gestión de marcas'),
('Emilia Vargas', 'Mercadeo', 10, 'Marketing digital y comercio electrónico'),
('Miguel Morales', 'Diseño Gráfico', 2, 'Animación digital'),
('Sara Calle', 'Ingeniería Industrial', 9, 'Gestión logística en cadena de suministro'),
('Juan Pablo Jaramillo', 'Ingeniería de Sistemas', 4, 'Desarrollo de videojuegos'),
('Catalina Mejía', 'Comunicación Social', 6, 'Montaje audiovisual'),
('Felipe Cadavid', 'Administración de Empresas', 3, 'Gestión de proyectos de construcción sostenible'),
('Marisol Gallego', 'Psicología', 7, 'Economía circular y sostenibilidad'),
('Lucas Restrepo', 'Derecho', 5, 'Inteligencia artificial para mercadeo'),
('Valentina Estrada', 'Mercadeo', 8, 'Producción audiovisual para el metaverso'),
('Jorge Tabares', 'Diseño Gráfico', 10, 'Fotografía comercial');
